import {expect} from 'chai';

export const checkApi = api => {
    expect(Object.keys(api)).to.include.members([
        'numColumns',
        'numRows',
        'size',
        'valueAt',
        'row',
        'column',
        'moveCell',
        'moveRow',
        'moveColumn',
        'addRow',
        'addColumn',
        'removeRow',
        'removeColumn',
        'clipAt',
        'swapCells',
        'swapRows',
        'swapColumns',
        'fill',
        'find',
        // 'areaFitsAt',
        // 'setAreaAt',
        // 'getAreaAt',
        // 'findInArea',
        // 'positionInArea',
        // 'reduceAreaAt',
        'data',
        'list',
        'rotate',
        'flipX',
        'flipY',
        'map',
        'forEach',
        'reduce',
        'clone',
        'adjacentCellsAt',
        'area',
    ]);
};